env:
  browser: false
  node: true
extends:
  - plugin:@ianwremmel/ianwremmel/modern
  - prettier
overrides:
  - env:
      node: true
    files:
      - '*.config.js'
    parserOptions:
      sourceType: script
    rules:
      strict:
        - error
        - global
  - env:
      jest: true
    files:
      - '**/*.spec.*'
    rules:
      require-jsdoc: off
  - files:
      - '**/*.ts'
    parser: '@typescript-eslint/parser'
    parserOptions:
      project: ./tsconfig.json
    rules:
      import/export: off
      import/no-unresolved: off
      no-redeclare: off
      no-unused-vars: off
      valid-jsdoc: off
parserOptions:
  sourceType: module
rules:
  compat/compat: off
  new-cap:
    - error
    - capIsNewExceptions:
        - Router
  no-restricted-syntax: off
  require-jsdoc: off
